builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/karimra/gnmiClient/cmd.version={{.Version}} -X github.com/karimra/gnmiClient/cmd.commit={{.ShortCommit}} -X github.com/karimra/gnmiClient/cmd.date={{.Date}} -X github.com/karimra/gnmiClient/cmd.gitURL={{.GitURL}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    hooks:
      post: upx --brute "{{ .Path }}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
      386: i386
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
