global:
  scrape_interval:     10s 
  evaluation_interval: 10s 

scrape_configs:
  - job_name: 'gnmic'
    scrape_interval: 10s 
    consul_sd_configs:
      - server: clab-lab110-consul-agent:8500

  - job_name: 'gnmic-internal'
    scrape_interval: 10s 
    static_configs:
      - targets:
        - clab-lab110-gnmic:7890
