username: admin
password: admin
skip-verify: true
log: true

loader:
  type: docker
  filters:
    - containers:
      - label=clab-node-kind: srl
        label=containerlab: lab110

subscriptions:
  # Add subscriptions configuration here
  # e.g:
  sub1:
    paths:
      - /interface[name=*]/statistics
      - /interface[name=*]/description
    stream-mode: sample
    sample-interval: 10s
    encoding: ascii
  sub2:
    paths:
      - /acl/cpm-filter/ipv4-filter/entry/statistics
      - /acl/cpm-filter/ipv6-filter/entry/statistics
    stream-mode: sample
    sample-interval: 10s
    encoding: ascii 

outputs:
  prom-output-redis:
    type: prometheus
    listen: "clab-lab110-gnmic:9804"
    service-registration:
      address: clab-lab110-consul-agent:8500
    event-processors:
      - group_by_interface
    cache:
      type: redis
      address: "clab-lab110-redis:6379"

  prom-output-nats:
    type: prometheus
    listen: "clab-lab110-gnmic:9805"
    service-registration:
      address: clab-lab110-consul-agent:8500
    event-processors:
      - group_by_interface
    cache:
      type: nats

  prom-output-js:
    type: prometheus
    listen: "clab-lab110-gnmic:9806"
    service-registration:
      address: clab-lab110-consul-agent:8500
    event-processors:
      - group_by_interface
    cache:
      type: jetstream

  prom-output-oc:
    type: prometheus
    listen: "clab-lab110-gnmic:9807"
    service-registration:
      address: clab-lab110-consul-agent:8500
    event-processors:
      - group_by_interface
    cache: {}

processors:
  group_by_interface:
    event-group-by:
      tags:
        - target
        - interface_name

api-server:
  enable-metrics: true