---
name: Linter
on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - "main"
  #     - "!releases/**"
  
env:
  GOVER: 1.18.1

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVER }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.46
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --verbose --max-same-issues=0 --max-issues-per-linter=0  --out-format=github-actions

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true